name: flame_svg
description: Package to add SVG rendering support for the Flame game engine
version: 0.0.1
homepage: https://github.com/flame-engine/flame_svg

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.18.0-6.0.pre <2.0.0"

dependencies:
  flame: '1.0.0-rc2'
  flutter_svg: ^0.19.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
